<ul class="products columns-1">
    <div class="items_container container p-0">
        <div class="row">
            
<div class="col-md-3 col-6 p-0">

    <div class="product type-product post-115 status-publish first instock product_cat-marvel has-post-thumbnail shipping-taxable purchasable product-type-simple">
        <a href="http://localhost/Underground_comics/site/product/earths-mightiest-heros-the-avengers/" class="woocommerce-LoopProduct-link woocommerce-loop-product__link"><img width="255" height="383" src="http://localhost/Underground_comics/site/wp-content/uploads/2020/02/comic-255x383.jpg" class="attachment-woocommerce_thumbnail size-woocommerce_thumbnail" alt="Avengers" srcset="http://localhost/Underground_comics/site/wp-content/uploads/2020/02/comic-255x382.jpg 255w, http://localhost/Underground_comics/site/wp-content/uploads/2020/02/comic-200x300.jpg 200w, http://localhost/Underground_comics/site/wp-content/uploads/2020/02/comic.jpg 633w" sizes="(max-width: 255px) 100vw, 255px"><h2 class="woocommerce-loop-product__title">Earth’s mightiest heros the avengers</h2>    </a></div><a href="http://localhost/Underground_comics/site/product/earths-mightiest-heros-the-avengers/" class="woocommerce-LoopProduct-link woocommerce-loop-product__link">
</a></div><a href="http://localhost/Underground_comics/site/product/earths-mightiest-heros-the-avengers/" class="woocommerce-LoopProduct-link woocommerce-loop-product__link">
</a><div class="col-md-3 col-6 p-0"><a href="http://localhost/Underground_comics/site/product/earths-mightiest-heros-the-avengers/" class="woocommerce-LoopProduct-link woocommerce-loop-product__link">

    </a><div class="product type-product post-119 status-publish first instock product_cat-marvel has-post-thumbnail shipping-taxable purchasable product-type-simple"><a href="http://localhost/Underground_comics/site/product/earths-mightiest-heros-the-avengers/" class="woocommerce-LoopProduct-link woocommerce-loop-product__link">
        </a><a href="http://localhost/Underground_comics/site/product/earths-mightiest-heros-the-avengers-copy/" class="woocommerce-LoopProduct-link woocommerce-loop-product__link"><img width="255" height="383" src="http://localhost/Underground_comics/site/wp-content/uploads/2020/02/comic-255x383.jpg" class="attachment-woocommerce_thumbnail size-woocommerce_thumbnail" alt="Avengers" srcset="http://localhost/Underground_comics/site/wp-content/uploads/2020/02/comic-255x382.jpg 255w, http://localhost/Underground_comics/site/wp-content/uploads/2020/02/comic-200x300.jpg 200w, http://localhost/Underground_comics/site/wp-content/uploads/2020/02/comic.jpg 633w" sizes="(max-width: 255px) 100vw, 255px"><h2 class="woocommerce-loop-product__title">Earth’s mightiest heros the avengers 2</h2>    </a></div><a href="http://localhost/Underground_comics/site/product/earths-mightiest-heros-the-avengers-copy/" class="woocommerce-LoopProduct-link woocommerce-loop-product__link">
</a></div><a href="http://localhost/Underground_comics/site/product/earths-mightiest-heros-the-avengers-copy/" class="woocommerce-LoopProduct-link woocommerce-loop-product__link">
</a><div class="col-md-3 col-6 p-0"><a href="http://localhost/Underground_comics/site/product/earths-mightiest-heros-the-avengers-copy/" class="woocommerce-LoopProduct-link woocommerce-loop-product__link">

    </a><div class="product type-product post-198 status-publish first instock product_cat-marvel has-post-thumbnail shipping-taxable purchasable product-type-simple"><a href="http://localhost/Underground_comics/site/product/earths-mightiest-heros-the-avengers-copy/" class="woocommerce-LoopProduct-link woocommerce-loop-product__link">
        </a><a href="http://localhost/Underground_comics/site/product/earths-mightiest-heros-the-avengers-copy-copy/" class="woocommerce-LoopProduct-link woocommerce-loop-product__link"><img width="255" height="383" src="http://localhost/Underground_comics/site/wp-content/uploads/2020/02/comic-255x383.jpg" class="attachment-woocommerce_thumbnail size-woocommerce_thumbnail" alt="Avengers" srcset="http://localhost/Underground_comics/site/wp-content/uploads/2020/02/comic-255x382.jpg 255w, http://localhost/Underground_comics/site/wp-content/uploads/2020/02/comic-200x300.jpg 200w, http://localhost/Underground_comics/site/wp-content/uploads/2020/02/comic.jpg 633w" sizes="(max-width: 255px) 100vw, 255px"><h2 class="woocommerce-loop-product__title">Earth’s mightiest heros the avengers 3</h2>    </a></div><a href="http://localhost/Underground_comics/site/product/earths-mightiest-heros-the-avengers-copy-copy/" class="woocommerce-LoopProduct-link woocommerce-loop-product__link">
</a></div><a href="http://localhost/Underground_comics/site/product/earths-mightiest-heros-the-avengers-copy-copy/" class="woocommerce-LoopProduct-link woocommerce-loop-product__link">
</a><div class="col-md-3 col-6 p-0"><a href="http://localhost/Underground_comics/site/product/earths-mightiest-heros-the-avengers-copy-copy/" class="woocommerce-LoopProduct-link woocommerce-loop-product__link">

    </a><div class="product type-product post-199 status-publish first instock product_cat-marvel has-post-thumbnail shipping-taxable purchasable product-type-simple"><a href="http://localhost/Underground_comics/site/product/earths-mightiest-heros-the-avengers-copy-copy/" class="woocommerce-LoopProduct-link woocommerce-loop-product__link">
        </a><a href="http://localhost/Underground_comics/site/product/earths-mightiest-heros-the-avengers-4/" class="woocommerce-LoopProduct-link woocommerce-loop-product__link"><img width="255" height="383" src="http://localhost/Underground_comics/site/wp-content/uploads/2020/02/comic-255x383.jpg" class="attachment-woocommerce_thumbnail size-woocommerce_thumbnail" alt="Avengers" srcset="http://localhost/Underground_comics/site/wp-content/uploads/2020/02/comic-255x382.jpg 255w, http://localhost/Underground_comics/site/wp-content/uploads/2020/02/comic-200x300.jpg 200w, http://localhost/Underground_comics/site/wp-content/uploads/2020/02/comic.jpg 633w" sizes="(max-width: 255px) 100vw, 255px"><h2 class="woocommerce-loop-product__title">Earth’s mightiest heros the avengers 4</h2>    </a></div><a href="http://localhost/Underground_comics/site/product/earths-mightiest-heros-the-avengers-4/" class="woocommerce-LoopProduct-link woocommerce-loop-product__link" style="
    height: 100px;
    width: 100px;
    border: 3px solid orangered;
">
</a></div><a href="http://localhost/Underground_comics/site/product/earths-mightiest-heros-the-avengers-4/" class="woocommerce-LoopProduct-link woocommerce-loop-product__link">        </a></div><a href="http://localhost/Underground_comics/site/product/earths-mightiest-heros-the-avengers-4/" class="woocommerce-LoopProduct-link woocommerce-loop-product__link">
    </a></div><a href="http://localhost/Underground_comics/site/product/earths-mightiest-heros-the-avengers-4/" class="woocommerce-LoopProduct-link woocommerce-loop-product__link">
</a></ul>